CREATE TABLE TRANSACTIONS (
	ID INT IDENTITY(1,1), 
	ACCOUNT_NUMBER VARCHAR(15) NOT NULL,
	ACCOUNT_TYPE VARCHAR(15) NOT NULL,
	PROCESSING_DATE VARCHAR(15) NOT NULL,
	BALANCE VARCHAR(15) NOT NULL,
	TRANSACTION_TYPE VARCHAR(10) NOT NULL,
	TRANSACTION_AMOUNT VARCHAR(15) NOT NULL,
	TRANSACTION_DESCRIPTION VARCHAR(40) NOT NULL,
	TRANSACTION_TIME VARCHAR (10) NOT NULL,
	TRANSACTION_STATE VARCHAR (5) NOT NULL

	PRIMARY KEY (ID)
);