USE commerceDB;

GO

CREATE PROCEDURE CREATE_TRANSACTION 
	@ACCOUNT_NUMBER VARCHAR(15),
	@ACCOUNT_TYPE VARCHAR(15),
	@PROCESSING_DATE VARCHAR(15),
	@BALANCE VARCHAR(15),
	@TRANSACTION_TYPE VARCHAR(10),
	@TRANSACTION_AMOUNT VARCHAR(15),
	@TRANSACTION_DESCRIPTION VARCHAR(40),
	@TRANSACTION_TIME VARCHAR(10),
	@TRANSACTION_STATE VARCHAR (5)
	
AS 

	BEGIN 
	INSERT INTO TRANSACTIONS (ACCOUNT_NUMBER, ACCOUNT_TYPE, PROCESSING_DATE, BALANCE, TRANSACTION_TYPE, TRANSACTION_AMOUNT, TRANSACTION_DESCRIPTION, TRANSACTION_TIME, TRANSACTION_STATE) VALUES (
	@ACCOUNT_NUMBER,
	@ACCOUNT_TYPE,
	@PROCESSING_DATE,
	@BALANCE,
	@TRANSACTION_TYPE,
	@TRANSACTION_AMOUNT,
	@TRANSACTION_DESCRIPTION,
	@TRANSACTION_TIME,
	@TRANSACTION_STATE
); 
	END