USE commerceDB;

GO

CREATE PROCEDURE CREATE_NOTIFICATION
	@ACCOUNT_NUMBER VARCHAR(15),
	@TRIGGER_MESSAGE VARCHAR(100)

AS 

	BEGIN
	INSERT INTO TRANSAC_NOTIFICATIONS (ACCOUNT_NUMBER, TRIGGER_MESSAGE) VALUES (
	@ACCOUNT_NUMBER,
	@TRIGGER_MESSAGE
);

	END