USE commerceDB;

GO

CREATE PROCEDURE CREATE_NOTIFICATION
	@TRANSACTION_ID VARCHAR(5),
	@ACCOUNT_NUMBER VARCHAR(15),
	@TRIGGER_MESSAGE VARCHAR(100)

AS 

	BEGIN
	INSERT INTO TRANSAC_NOTIFICATIONS (TRANSACTION_ID, ACCOUNT_NUMBER, TRIGGER_MESSAGE) VALUES (
	@TRANSACTION_ID,
	@ACCOUNT_NUMBER,
	@TRIGGER_MESSAGE
);

	END