CREATE TABLE CUSTOMER_TABLE (
	FIRST CHAR(15) NOT NULL,
	LAST CHAR(15) NOT NULL,
	EMAIL CHAR(50) NOT NULL,
	CHECKING INT,
	SAVINGS INT,
	PRIMARY KEY (EMAIL)
);

CREATE TABLE TRANSACTIONS (
	CUSTOMER_ID INT NOT NULL PRIMARY KEY,
	DATE INT NOT NULL,
	AMOUNT INT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	LOCATION TEXT NOT NULL
);