USE commerceDB;

GO

CREATE PROCEDURE CREATE_TRIGGER
	@ACCOUNT_NUMBER VARCHAR(15),
	@TRIGGER_TYPE VARCHAR(20),
	@TRIGGER_VALUE VARCHAR(35)

AS
	
	BEGIN
	INSERT INTO TRANSAC_TRIGGERS (ACCOUNT_NUMBER, TRIGGER_TYPE, TRIGGER_VALUE) VALUES (
	@ACCOUNT_NUMBER,
	@TRIGGER_TYPE,
	@TRIGGER_VALUE
);

	END