USE commerceDB;

GO

CREATE PROCEDURE REMOVE_TRIGGER
	@ACCOUNT_NUMBER VARCHAR(15),
	@TRIGGER_TYPE VARCHAR(20),
	@TRIGGER_VALUE VARCHAR(35)

AS

	BEGIN
	DELETE FROM TRANSAC_TRIGGERS WHERE @ACCOUNT_NUMBER = ACCOUNT_NUMBER AND @TRIGGER_TYPE = TRIGGER_TYPE AND @TRIGGER_VALUE = TRIGGER_VALUE;

	END